apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: argocd
project: default
source:
  repoURL: 'https://github.com/vBardys/ArgoCD'
  path: backend
  targetRevision: main
destination:
  server: 'https://kubernetes.default.svc'
  namespace: default
syncPolicy:
  automated: {}
